### PR TITLE
Automate publication queries

### LINKED ISSUE #10: Some papaya pages don't work quite right
mod_t2w.html and mod_t1w.html are examples that don't work. However, acq_aomovie.html works just fine.

I'm not quite sure what's up.

---Alex

### PR DESCRIPTION
**Pull request by adswa**
This fixes https://github.com/psychoinformatics-de/studyforrest-data/issues/10 and https://github.com/psychoinformatics-de/studyforrest-data/issues/32 . It adds a commandline tool to search pubmed for citing research of any of the studyforrest data descriptors. When it finds new citing research, it extends a JSON data base with all previously found articles. The articles are listed with the metadata Pubmed provides.
Based on a subset of the metadata, the tool recreates the current publications HTML table from the website with an up-to-date list.

By default, new research is not categorized and will be listed as "citing" the studyforrest data in the resulting HTML table. If a human user wants to amend this category into "data" or "study", they can replace the "TODO" value in the respective ``articletype`` key in the ``article_database.json`` file.

The tool operates without command line arguments, but one can supply different PMCIDs to find additional citations for with the ``--ids`` flag, surpress the generation of an HTML table to ``--nohtml``, and can point to a different data base file with the ``-d/--database`` argument.

I have annotated the data base with missing articles (e.g., unpublished and thus not indexed), and categories.

### CODE REVIEW

**Comment by adswa** [comment]
Oh, found a bug. Don't merge

**Comment by adswa** [comment]
Pushed a fix! Feel free to play around with it. cc @mih

**Comment by aqw** [comment]
This looks good to me. I'm happy to merge, but as @mih will be the primary user, I'll wait for his thoughts.

**Comment by aqw** [comment]
Looks like mih is too cool to look at this. Merging, because it deserves it. :-D

Thanks!

**Pull request merged**
